version: '3.8'

services:
  whatsapp-api:
    build:
      context: .
      target: ${TARGET:-builder}  # Default to builder for development
    image: whatsapp-mcp:${TAG:-dev}
    container_name: whatsapp-mcp
    ports:
      - "${PORT:-3000}:3000"
    environment:
      - NODE_ENV=${NODE_ENV:-development}
      - PORT=3000
      # Add other environment variables as needed
    volumes:
      - .:/app
      - /app/node_modules
      - /app/dist
    command: ${COMMAND:-npm run dev}  # Default to dev for development
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/health"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 5s
    restart: unless-stopped
    networks:
      - whatsapp-network

networks:
  whatsapp-network:
    driver: bridge 